### PR TITLE
Organiser placeholders

### PR DESCRIPTION
**Pull request by judy2k**
I've added records for all organisers, so they're all there.

Most are placeholders. Hopefully each organiser can update the records themselves!

### CODE REVIEW

**Comment by judy2k** [comment]
Fixes #7

**Review by rebkwok — COMMENTED** [review]
LGTM. Suggest changing "DjangoCon EU to DjangoConEurope" in the into text on the organisers page.

**Review by sabderemane — COMMENTED** [review]
Hi @judy2k 😄
I think it's missing to update the readme if someone wants to change something.

But I've seen others places using organizers folder, maybe change everywhere to the British spelling? (I'm not 100% sure about that) 

@thibaudcolas @knyghty any recommendations?

**Review by thibaudcolas — APPROVED** [review]
Profiles are looking great, there’s a bit of cleanup to do but I can pick this up when merging. Thank you @judy2k!

**Pull request merged**
